name: Build when push
on:
  push:
    branches:
      - main
jobs:
  build-test-upload:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Upload
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: dist
  recover:
      needs: [build-test-upload]
      name: Recover artifact
      runs-on: ubuntu-latest
      steps:
        - name: Get build artifac
          uses: actions/download-artifact@v4
          with:
            name: dist-files
            path: dist
        - name: Show files
          run: ls